### ISSUE TITLE
貌似好久没更新了，fis3用不起。这个还会继续维护吗？

### ISSUE THREAD

**Issue by DeyuanTan** [qdsang/fis-parser-compass#4]
如题。

**Comment by qdsang** [comment]
@DeyuanTan 可以提交个PR   sass 插件需要换成 node-sass

**Comment by DeyuanTan** [comment]
试过用 node-sass了，但是还是没办法使用 image-width 这一类的函数获取图片的宽度，release之后会原样输出，不知道什么原因。https://github.com/fex-team/fis3/issues/270
